import { useState } from 'react';
import { analyzeFarmerProblem, generateApplicationDraft, matchSchemes } from '../services/schemeService';
import './schemeIntelligence.css';
import './schemeRecommendations.css';
import './schemeContextPrompt.css';

const processingSteps = ['Understanding problem', 'Identifying crop and loss', 'Checking scheme rules', 'Finding potentially relevant schemes', 'Preparing recommendations'];
const fieldConfig = [['Full Name', 'fullName', 'text'], ['Mobile Number', 'mobile', 'tel'], ['State', 'state', 'text'], ['District', 'district', 'text'], ['Village', 'village', 'text'], ['Crop', 'crop', 'text'], ['Cultivated Area', 'cultivatedArea', 'text'], ['Affected Area', 'affectedArea', 'text'], ['Date of Loss', 'lossDate', 'date'], ['Cause of Loss', 'cause', 'text']];
const prettyIntent = intent => intent.replaceAll('_', ' ').replace(/\b\w/g, letter => letter.toUpperCase());

export default function SchemeIntelligence() {
  const [description, setDescription] = useState('Heavy rainfall damaged most of my tomato crop.');
  const [stage, setStage] = useState('input'); const [analysis, setAnalysis] = useState(null); const [matches, setMatches] = useState([]); const [selectedScheme, setSelectedScheme] = useState(null); const [details, setDetails] = useState({}); const [draft, setDraft] = useState(null);
  function analyze(problem = description) { const result = analyzeFarmerProblem(problem); setStage('processing'); setTimeout(() => { const recommendations = matchSchemes(result); setAnalysis(result); setMatches(recommendations); setSelectedScheme(recommendations[0] || null); setDetails(current => ({ ...current, crop: result.crop === 'Not specified' ? '' : result.crop, cause: result.cause === 'Not specified' ? '' : result.cause, affectedArea: result.affectedArea === 'Not specified' ? '' : result.affectedArea, state: result.location === 'Not specified' ? '' : result.location })); setStage('results'); }, 2100); }
  function refineStorageContext(produce, role) { const refinedProblem = `${description} I am a ${role} and need storage for harvested ${produce}.`; setDescription(refinedProblem); analyze(refinedProblem); }
  function selectScheme(scheme) { setSelectedScheme(scheme); setStage('details'); }
  function continueDetails(event) { event.preventDefault(); setStage('summary'); }
  function prepareDraft() { setDraft(generateApplicationDraft(details, selectedScheme)); setStage('draft'); }
  return <section className="scheme-intelligence"><div className="scheme-intro"><div><label>AI-ASSISTED DISCOVERY · PROTOTYPE</label><h2>Tell us what happened.</h2><p>We’ll help identify potentially relevant government schemes and services.</p></div><div className="scheme-flow">PROBLEM <span>↓</span> AI UNDERSTANDS <span>↓</span> SCHEME MATCHING <span>↓</span> OFFICIAL PORTAL</div></div>
    {stage === 'input' && <div className="scheme-input"><label>DESCRIBE YOUR FARM PROBLEM</label><textarea value={description} onChange={event => setDescription(event.target.value)} placeholder="Describe what happened to your farm..." /><small>Example: Heavy rainfall damaged most of my tomato crop.</small><button className="primary" onClick={() => analyze()}>✦ Analyze My Problem</button></div>}
    {stage === 'processing' && <div className="scheme-processing"><i>✦</i><label>AGRICONNECT AI IS ANALYZING</label><h3>Finding the most relevant support pathways</h3>{processingSteps.map((step, index) => <div key={step} style={{ animationDelay: `${index * .32}s` }}><b>✓</b>{step}{index < processingSteps.length - 1 && <span>↓</span>}</div>)}</div>}
    {stage === 'results' && <div className="scheme-results"><div className="analysis-panel"><label>AI UNDERSTANDING · BASED ON INFORMATION PROVIDED</label><h3>Problem</h3><b>{analysis.intents.length ? prettyIntent(analysis.intents[0]) : 'General support enquiry'}</b><p className="detected-intents">Detected intent: {analysis.intents.length ? analysis.intents.map(prettyIntent).join(' · ') : 'Not yet specific enough'}</p><div className="analysis-grid"><span>Crop<strong>{analysis.crop}</strong></span><span>Cause<strong>{analysis.cause}</strong></span><span>Affected area<strong>{analysis.affectedArea}</strong></span><span>Location<strong>{analysis.location}</strong></span></div>{analysis.missingInformation.includes('whatToStore') && <div className="context-prompt"><b>Your problem appears related to storage.</b><p>What are you trying to store?</p><div><button onClick={() => refineStorageContext('crops', 'farmer')}>Harvested crops</button><button onClick={() => refineStorageContext('fruits and vegetables', 'farmer')}>Fruits / vegetables</button><button onClick={() => refineStorageContext('grains', 'FPO')}>Grains · FPO</button></div></div>}</div><div className="recommendation-list">{matches.length ? matches.map(scheme => <div className="recommendation-card" key={scheme.id}><label>POTENTIALLY RELEVANT · {scheme.relevance.toUpperCase()} RELEVANCE</label><h2>{scheme.name}</h2><h4>{scheme.category.replaceAll('-', ' ')}</h4><div><b>Why this was identified:</b><p>{scheme.reason}</p></div><small>Potentially relevant based on the information provided. Final eligibility is determined by official scheme rules and applicable notifications.</small><div className="actions"><button className="primary" onClick={() => selectScheme(scheme)}>Check My Details</button><a className="secondary" href={scheme.officialUrl} target="_blank" rel="noreferrer">View Official Details ↗</a></div></div>) : <div className="recommendation-card no-match"><label>MORE INFORMATION NEEDED</label><h2>We couldn’t identify a potentially relevant scheme yet.</h2><p>Could you tell us a little more about the problem, crop, location or support you need?</p><button className="secondary" onClick={() => setStage('input')}>Edit description</button></div>}</div></div>}
    {stage === 'details' && <form className="farmer-details" onSubmit={continueDetails}><label>FARMER DETAILS · FOR RELEVANCE CHECK</label><h3>Help complete your application draft for {selectedScheme.name}.</h3><p>Only enter information you are comfortable using in this prototype.</p><div className="detail-grid">{fieldConfig.map(([label, key, type]) => <label key={key}>{label}<input required value={details[key] || ''} type={type} onChange={event => setDetails({ ...details, [key]: event.target.value })} /></label>)}<label>Was the crop insured?<select required value={details.insured || ''} onChange={event => setDetails({ ...details, insured: event.target.value })}><option value="">Select an option</option><option>Yes</option><option>No</option><option>Don't Know</option></select></label></div><button className="primary">Continue →</button></form>}
    {stage === 'summary' && <div className="eligibility-summary"><label>ELIGIBILITY / RELEVANCE CHECK</label><h2>Potentially relevant: <em>{selectedScheme.name}</em></h2><div className="summary-grid"><div><b>Information provided</b><p>✓ Crop<br />✓ Location<br />✓ Problem details<br />✓ Loss or request date<br />✓ Area or support context</p></div><div><b>Information that may still be required</b><p>• Insurance/application details<br />• Scheme/notification applicability<br />• Other official documentation</p></div></div><p className="official-warning">Final eligibility and claim approval are determined by the relevant government/insurance authority.</p><button className="primary" onClick={prepareDraft}>Prepare Application</button></div>}
    {stage === 'draft' && <div className="application-draft"><label>PRE-FILLED APPLICATION DRAFT · NOT SUBMITTED</label><h2>{draft.scheme}</h2><div className="draft-grid">{[['Applicant', draft.applicant], ['State', draft.state], ['District', draft.district], ['Crop', draft.crop], ['Affected Area', draft.affectedArea], ['Cause', draft.cause], ['Date of Loss', draft.lossDate]].map(([label, value]) => <div key={label}><small>{label}</small><b>{value}</b></div>)}</div><p>This draft is for your review. AgriConnect does not submit applications to government systems.</p><div className="actions"><button className="secondary" onClick={() => setStage('details')}>Edit Details</button><a className="primary" href={draft.officialUrl} target="_blank" rel="noreferrer">Continue to Official Portal ↗</a></div></div>}
    {stage !== 'input' && stage !== 'processing' && <button className="text-button" onClick={() => setStage('input')}>← Analyze another problem</button>}</section>;
}
