import { schemes } from '../data/schemes.js';

const replacements = [['post-harvest', 'post harvest'], ['postharvest', 'post harvest'], ['centre', 'center'], ['organisation', 'organization'], ['warehouses', 'warehouse'], ['buyers', 'buyer'], ['crops', 'crop'], ['vegetables', 'vegetable'], ['fruits', 'fruit'], ['hail storm', 'hailstorm'], ['heavy rains', 'heavy rain'], ['rains', 'rain']];
const intentDictionary = {
  crop_loss: ['crop loss', 'crop lost', 'lost crop', 'crop destroyed', 'crop ruined', 'harvest lost', 'produce lost', 'field damaged', 'farm damaged'], crop_damage: ['crop damaged', 'damaged crop', 'damage to crop', 'my crop was damaged'], weather_damage: ['heavy rain', 'heavy rainfall', 'excess rain', 'unseasonal rain', 'flood', 'flooding', 'hail', 'hailstorm', 'drought', 'cyclone', 'storm', 'weather event'], flood_damage: ['flood', 'flooding', 'inundation'], drought_damage: ['drought', 'dry spell'], hail_damage: ['hail', 'hailstorm'], cyclone_damage: ['cyclone'], pest_damage: ['pest', 'insect attack'], disease_damage: ['disease', 'blight', 'fungus'], crop_insurance: ['crop insurance', 'insured crop'], insurance_claim: ['insurance claim', 'claim for crop'],
  market_access: ['market', 'market access', 'sell crop', 'sell produce', 'selling crop', "can't sell", 'cannot sell', 'unable to sell', 'find buyer', 'need buyer', 'no buyer', 'buyer problem', 'market linkage'], no_buyer: ['no buyer', 'nobody buying', 'nobody is buying', 'cannot find buyer', 'unable to find buyer'], buyer_problem: ['buyer problem', 'buyer not available'], selling_problem: ["can't sell", 'cannot sell', 'unable to sell'], low_price: ['low price', 'poor price', 'bad price', 'less price', 'low market rate', 'trader offering less', 'not getting good price'], price_discovery: ['better price', 'price discovery', 'market rate'], better_market: ['better market', 'better agricultural market'], market_linkage: ['market linkage'],
  income_support: ['income support', 'income assistance', 'money support', 'pm kisan'], financial_support: ['financial support', 'financial help'], farmer_support: ['farmer support'], farmer_income: ['farmer income'], farmer_financial_support: ['support available for farmer'],
  fpo_creation: ['form an fpo', 'create an fpo', 'fpo formation', 'register an fpo'], fpo_support: ['fpo support', 'our fpo', 'farmer organization'], fpo_strengthening: ['strengthen fpo', 'strengthening our fpo'], farmer_group: ['farmer group', 'group of farmer'], collective_farming: ['collective farming'],
  storage: ['storage', 'store', 'storage issue', 'storage problem', 'storage facility', 'need storage', 'lack of storage', 'produce storage', 'crop storage'], warehouse: ['warehouse', 'warehouse issue', 'warehouse problem'], cold_storage: ['cold storage'], cold_chain: ['cold chain'], post_harvest: ['post harvest', 'harvested produce', 'after harvest'], collection_center: ['collection center'], infrastructure: ['infrastructure'], logistics: ['logistics', 'transport facility'], farm_infrastructure: ['farm infrastructure'],
};
const crops = ['tomato', 'potato', 'onion', 'wheat', 'rice', 'paddy', 'maize', 'cotton', 'soybean', 'vegetable', 'fruit', 'grain', 'produce'];
const locations = ['noida', 'uttar pradesh', 'haryana', 'rajasthan', 'delhi', 'punjab', 'maharashtra', 'madhya pradesh', 'bihar'];
const unrelatedContexts = ['personal file', 'personal files', 'computer file', 'car insurance', 'insurance for my car', 'mobile phone', 'buy a phone'];
const titleCase = value => value.split(' ').map(word => word[0].toUpperCase() + word.slice(1)).join(' ');

export function normalizeText(input = '') { let text = input.toLowerCase().trim().replace(/[–—-]/g, ' ').replace(/\s+/g, ' '); replacements.forEach(([from, to]) => { text = text.replaceAll(from, to); }); return text; }
export function detectIntents(normalizedText) { return Object.entries(intentDictionary).filter(([, phrases]) => phrases.some(phrase => normalizedText.includes(phrase))).map(([intent]) => intent); }
export function extractProblemDetails(input) { const description = normalizeText(input); const intents = detectIntents(description); const crop = crops.find(item => description.includes(item)); const location = locations.find(item => description.includes(item)); const cause = ['hailstorm', 'flood', 'inundation', 'drought', 'cyclone', 'unseasonal rain', 'heavy rainfall', 'heavy rain', 'rainfall', 'rain', 'pest', 'disease'].find(item => description.includes(item)); const areaMatch = description.match(/(\d+(?:\.\d+)?)\s*(?:acres?|%|percent)/); const agriculturalContext = Boolean(crop || /farm|farmer|field|harvest|agricultur|produce|grain|vegetable|fruit|fpo/.test(description)); const unrelated = unrelatedContexts.some(context => description.includes(context)); const storageNeedsContext = intents.some(intent => ['storage', 'warehouse', 'cold_storage', 'cold_chain'].includes(intent)) && !agriculturalContext; return { description, normalizedText: description, intents, problemType: intents[0] || 'general_support', crop: crop ? titleCase(crop) : 'Not specified', cause: cause ? titleCase(cause) : 'Not specified', affectedArea: areaMatch ? areaMatch[0] : 'Not specified', location: location ? titleCase(location) : 'Not specified', agriculturalContext, unrelated, status: unrelated || !intents.length ? 'needs_more_information' : 'analyzed', missingInformation: storageNeedsContext ? ['whatToStore', 'farmerRole'] : [] }; }
function explanationFor(scheme, analysis) { const text = analysis.normalizedText; if (scheme.id === 'pmfby') return 'Your description indicates crop loss, crop damage, insurance or an adverse agricultural event.'; if (scheme.id === 'enam') return 'Your problem relates to finding buyers, selling agricultural produce or price discovery.'; if (scheme.id === 'fpo') return 'Your description refers to FPO formation, farmer groups or strengthening an existing FPO.'; if (scheme.id === 'aif') return analysis.agriculturalContext ? 'Your description refers to agricultural storage, warehouse, cold-chain or post-harvest infrastructure.' : 'Your problem appears related to storage. Tell us what agricultural produce you are trying to store to refine this pathway.'; if (scheme.id === 'pm-kisan') return 'Your description asks about farmer income or financial support.'; return `Potentially relevant based on: ${text}.`; }
export function findPotentialSchemes(analysis) { if (analysis.unrelated) return []; const text = analysis.normalizedText; return schemes.map(scheme => { const matchedIntents = scheme.problemTypes.filter(intent => analysis.intents.includes(intent)); const strongKeywords = scheme.keywords.filter(keyword => text.includes(normalizeText(keyword))); const causeMatches = scheme.causes.filter(cause => text.includes(normalizeText(cause))); let score = matchedIntents.length * 50 + strongKeywords.length * 25 + causeMatches.length * 15; if (analysis.agriculturalContext && ['pmfby', 'enam', 'aif'].includes(scheme.id)) score += 10; if (analysis.unrelated) score -= 30; return { ...scheme, score, relevance: score >= 100 ? 'high' : score >= 50 ? 'medium' : 'related', intentMatches: matchedIntents, reason: explanationFor(scheme, analysis) }; }).filter(scheme => scheme.score >= 50).sort((a, b) => b.score - a.score); }
